export const _ABSFilamentDescription = "A durable and great material for general-purpose projects. Acrylonitrile butadiene styrene (ABS) filament is available in a wide range of colours.\n\n**Difficulty Level**: Intermediate\n\n**Strength**: High\n\n**Flexibility**: Medium\n\n**Durability**: High\n\n**Shrinkage/Warping**: Considerable\n\n**Soluble**: In esters, ketones, and acetone\n\n**Food safe**: No\n\n**Perfect for**: Frequently handled projects that may be dropped or heated, like phone cases and electrical enclosures\n\n## Printing Details\n\n**Print temperature**: 210 – 250°C\n\n**Heated Bed**: 80 – 110°C (required)\n\n## More Details\n\n**Pros**\n - Superior quality to PLA filament\n - No off-putting odor\n - Strong, durable, and temperature resistant\n\n**Cons**\n - Difficult to print\n - Harsh fumes\n - Prone to warping without the use of a heated bed\n";
export const _ABSFilamentTitle = "# 1.75mm ABS Filament\n";
export const _NylonFilamentDescription = "A popular synthetic polymer. Nylon or polyamide (PA) is a go-to filament material for 3D printing and is available in a wide range of colours.\n\n**Difficulty Level**: Intermediate\n\n**Strength**: Very High\n\n**Flexibility**: High\n\n**Durability**: High\n\n**Shrinkage/Warping**: Considerable\n\n**Soluble**: No\n\n**Food safe**: Yes\n\n**Perfect for**: Creating tools, functional prototypes, and mechanical parts like hinges or gears\n\n## Printing Details\n\n**Print temperature**: 240 – 260°C\n\n**Heated Bed**: 70 – 100°C (required)\n\n**Printing recommendations**: Use a high nozzle and heated printer bed for best results\n\n## More Details\n\n**Pros**\n\n - Can be dyed before or after the printing process\n - Strong, flexible, durable\n\n**Cons**\n\n - Must be stored in a cool, dry place to avoid absorbing moisture\n";
export const _NylonFilamentTitle = "# 1.75mm Nylon (PA) Filament\n";
export const _PCFilamentDescription = "One of the strongest 3D printer filaments, PC filament is durable and temperature resistant. It is available in a wide range of colours.\n\n**Difficulty Level**: Intermediate\n\n**Strength**: Very High\n\n**Flexibility**: Medium\n\n**Durability**: Very High\n\n**Shrinkage/Warping**: Considerable\n\n**Soluble**: No\n\n**Food safe**: No\n\n**Perfect for**: Projects that need to retain their strength and shape and may be exposed to high temperatures. PC material is clear which makes it great for projects that leverage transparency.\n\n## Printing Details\n\n**Print temperature**: 270 – 310°C\n\n**Heated Bed**: 90 – 110°C (required)\n\n## More Details\n\n**Pros**\n\n - Very strong, durable material that is resistant to high temperatures\n   and physical stress\n\n**Cons**\n\n - Must be stored in a cool, dry place to avoid absorbing moisture\n   Requires a very high print temperature\n";
export const _PCFilamentTitle = "# 1.75mm Polycarbonate (PC) Filament\n";
export const _PETGFilamentDescription = "Polyethylene terephthalate (PET) filament is a variant of one of the most used plastics in the world. It is available in a wide range of colours.\n\n**Difficulty Level**: Beginner\n\n**Strength**: High\n\n**Flexibility**: Medium\n\n**Durability**: High\n\n**Shrinkage/Warping**: Minimal\n\n**Soluble**: No\n\n**Food safe**: Yes\n\n**Perfect for**: Functional objects that may experience physical stress, like mechanical and protective parts\n\n## Printing Details\n\n**Print temperature**: 220 – 250°C\n\n**Heated Bed**: 50 – 75°C (required)\n\n**Printing recommendations**: Use a low print speed for a higher quality result\n\n## More Details\n\n**Pros**\n\n - A happy medium between PLA and ABS filaments\n - Clearer, less brittle, flexible, durable, and temperature resistant\n - Great for layer adhesion\n\n**Cons**\n\n - Sticky when printed\n - Scratches easily\n - Susceptible to moisture\n";
export const _PETGFilamentTitle = "# 1.75mm PETG Filament\n";
export const _PLAFilamentDescription = "The popular and easy-to-use 3D printer filament, polylactic acid (PLA), is available in a wide range of colours.\n\n**Difficulty Level**: Beginner\n\n**Strength**: Medium\n\n**Flexibility**: Low\n\n**Durability**: Medium\n\n**Shrinkage/Warping**: Minimal\n\n**Soluble**: No\n\n**Food safe**: Yes\n\n**Perfect for**: Non-mechanical prints like toys and figurines\n\n## Printing Details\n\n**Print temperature**: 180 – 230°C\n\n**Heated Bed**: Not required.\n\n## More Details\n\n**Pros**\n\n - Easy to use\n - No off-putting odor\n - More environmentally friendly (as compared to other 3D printer\n   filaments)\n\n**Cons**\n\n - Brittle: avoid using for projects that will be bent, twisted, or\n   dropped\n - Deforms above temperatures of 60°C\n";
export const _PLAFilamentGlowDescription = "The popular and easy-to-use 3D printer filament, polylactic acid (PLA), in a glow-in-the-dark variation! To activate, leave your print in the light for a while, then bring it into the dark to experience the glow.\n\n**Difficulty Level**: Beginner\n\n**Strength**: Medium\n\n**Flexibility**: Low\n\n**Durability**: Medium\n\n**Shrinkage/Warping**: Minimal\n\n**Soluble**: No\n\n**Food safe**: Yes\n\n**Perfect for**: Halloween projects, wearable prints like jewellery, toys, figurines\n\n## Printing Details\n\n**Print temperature**: 180 – 230°C\n\n**Heated Bed**: Not required.\n\n**Printing recommendations**: Print with thick walls and less infill for a stronger glow!\n\n## More Details\n\n**Pros**\n\n - Easy to use\n - No off-putting odor\n - More environmentally friendly (as compared to other 3D printer\n   filaments)\n\n**Cons**\n\n - Brittle: avoid using for projects that will be bent, twisted, or\n   dropped\n - Deforms above temperatures of 60°C\n";
export const _PLAFilamentGlowTitle = "# 1.75mm PLA Filament (Glow-in-the-dark)\n";
export const _PLAFilamentTitle = "# 1.75mm PLA Filament\n";
export const _TPEFilamentDescription = "A soft and stretchable plastic, thermoplastic elastomer (TPE) flexible filaments are available in a wide range of colours.\n\n**Difficulty Level**: Intermediate\n\n**Strength**: Medium\n\n**Flexibility**: Very High\n\n**Durability**: Very High\n\n**Shrinkage/Warping**: Minimal\n\n**Soluble**: No\n\n**Food safe**: No\n\n**Perfect for**: Prints that will experience a lot of physical wear and tear (bending, stretching, compressing) or harsh weather conditions. Great for toys, phone cases, wearable bands, household appliances, and medical supplies.\n\n## Printing Details\n\n**Print temperature**: 210 – 230°C\n\n**Heated Bed**: Not required\n\n**Printing recommendations**: Tight filament path and slow print speed are recommended\n\n## More Details\n\n**Pros**\n\n - Withstands physical stressors that ABS and PLA filaments can’t\n   tolerate\n\n**Cons**\n\n - Can be difficult to extrude\n";
export const _TPEFilamentTitle = "# 1.75mm TPE Flexible Filament";
export const _3DPenDescription = "Create 3D projects without software or files! With a 3D Pen you can draw and create 3D doodles on any flat surface. Draw and connect material in mid-air to create unique 3D master pieces.\n\n**Difficulty Level**: Beginner\n\n**Perfect for**: Kids, beginners, artists, and educators\n\n## How does a 3D pen work?\n\nThe plastic printing material is pushed through the pen, heated to the appropriate temperature, and leaves the pen in a soft, melted state. This malleable plastic hardens within a few seconds, taking the shape of your structure.\n\n## Filament Type\n\nABS: Best for beginners and drawing in mid-air\n\nPLA: Best for drawing directly onto flat surfaces\n\n";
export const _3DPenTitle = "# 3D Pen\n";
export const _CrealityEnder3AltText = "![Creality Ender 3 filament 3D printer. The printer is assembled and shows the frame, base and print bed, hotend, and display screen.](https://img.staticdj.com/78b4b1a181b236e46e401c5efe4df976_540x.jpg)";
export const _CrealityEnder3Description = "## Description\nThe Creality Ender 3 3D printer is an ideal printer for new and experienced 3D printing enthusiasts. The Ender 3 is semi-assembled, so you can assemble it quickly and get printing. The Creality Ender 3 3D printer has the following features:\n\n - Stable all-metal body\n - Hotbed reaches its maximum temperature in 5 minutes\n - Power-recovery mode allows you to resume printing after an unexpected power loss\n## Specifications\n**Technology**: FDM\n\n**Printing size**: 220x220x250mm\n\n**Filament types**: PLA, ABS, TPU, PETG\n\n**Maximum printing speed**: 180mm/s\n\n**Maximum bed temperature**: 110&deg;C\n\n**Maximum nozzle temperature**: 240&deg;C\n\n**Extruder**: Bowden\n\n**Build plate**: BuildTak-style sticker\n\n**Slicer software**: Cura, Repetier-Host, simplify3D";
export const _CrealityEnder3Title = "Creality Ender 3 Filament 3D Printer";
export const _CrealityEnder3ProAltText = "![Creality Ender 3 Pro filament 3D printer. The assembled printer has an all-metal body and a print bed with leveling nuts.](https://img.staticdj.com/1abb58d05800d58806f18e4c0157c790_540x.jpg)";
export const _CrealityEnder3ProDescription = "## Description\nThe Creality Ender 3 Pro 3D printer is an excellent printer for hobbyists and makers. The Ender 3 Pro is semi-assembled, so you can assemble it quickly and get printing. The Creality Ender 3 Pro 3D printer has the following features:\n\n - Magnetic build plate\n - Improved bearing wheels to reduce friction and create more stability\n - Power-recovery mode allows you to resume printing after an unexpected power loss\n## Specifications\n\n**Technology**: FDM\n\n**Printing size**: 220x220x250mm\n\n**Filament types**: PLA, ABS, TPU, PETG\n\n**Maximum printing speed**: 180mm/s\n\n**Maximum bed temperature**: 110&deg;C\n\n**Maximum nozzle temperature**: 240&deg;C\n\n**Extruder**: Bowden\n\n**Build plate**: “CMAG” magnetic plate\n\n**Slicer software**: Cura, Repetier-Host, simplify3D\n";
export const _CrealityEnder3ProTitle = "Creality Ender 3 Pro Filament 3D Printer";
export const _CrealityEnder3S1AltText = "![Creality Ender 3 S1 filament 3D printer. The assembled printer has white filament threaded into the extruder and a white figurine being printed onto the print bed.](https://img.staticdj.com/52d4e8a5e0a63066592527c8f8dc54f8_540x.jpg)";
export const _CrealityEnder3S1Description = "## Description\nThe Creality Ender 3 S1 3D printer is an excellent printer for experienced makers. The Ender 3 S1 is semi-assembled, so you can assemble it quickly and get printing. The Creality Ender 3 S1 3D printer has the following features:\n\n - Silent mainboard for quieter printing\n - Automatic bed leveling\n - New user interface for simple operation\n - Power-recovery mode allows you to resume printing after an unexpected power loss\n## Specifications\n**Technology**: FDM\n\n**Printing size**: 220x220x270mm\n\n**Filament types**: PLA, ABS, TPU, PETG\n\n**Maximum printing speed**: 150mm/s\n\n**Layer thickness**: 0.05-0.4mm\n\n**Maximum bed temperature**: 100&deg;C\n\n**Maximum nozzle temperature**: 260&deg;C\n\n**Extruder**: “Sprite” dual-gear direct extruder\n\n**Build plate**: PC spring steel magnetic build plate\n\n**Slicer software**: Cura";
export const _CrealityEnder3S1Title = "Creality Ender 3 S1 Filament 3D Printer";
export const _CrealityEnder3V2AltText = "![Creality Ender 3 V2 filament printer. The assembled printer has an all-metal body, compact base, enclosed hotend, and updated display panel.](https://img.staticdj.com/2e04a8d6247ebdb9fcc57b41bfd09a1c_540x.jpg)";
export const _CrealityEnder3V2Description = "## Description\nThe Creality Ender 3 V2 3D printer is an excellent printer for hobbyists and makers. The Ender 3 V2 is semi-assembled, so you can assemble it quickly and get printing. The Creality Ender 3 V2 3D printer has the following features:\n\n - Silent mainboard for quieter printing\n - High print quality\n - Power-recovery mode allows you to resume printing after an unexpected power loss\n## Specifications\n**Technology**: FDM\n\n**Printing size**: 220x220x250mm\n\n**Filament types**: PLA, ABS, TPU, PETG\n\n**Maximum printing speed**: 180mm/s\n\n**Layer thickness**: 0.1-0.4mm\n\n**Maximum bed temperature**: 110&deg;C\n\n**Maximum nozzle temperature**: 260&deg;C\n\n**Extruder**: Bowden\n\n**Build plate**: Carborundum glass\n\n**Slicer software**: Cura, simplify3D";
export const _CrealityEnder3V2Title = "Creality Ender 3 V2 Filament 3D Printer";
export const _ELEGOOMars2MonoAltText = "![ELEGOO Mars 2 Mono resin 3D printer. The printer has a transparent red UV cover that shows a white figurine being printed on the inverted build platform.](https://cdn.shopify.com/s/files/1/0296/9026/5648/products/elegoo-mars-2-mono-lcd-msla-resin-3d-printer-3d-printers-elegoo-shop-864685_2048x2048.jpg?v=1622707560)";
export const _ELEGOOMars2MonoDescription = "## Description\nThe ELEGOO Mars 2 Mono 3D printer is an ideal printer for new and experienced 3D printing enthusiasts. The Mars 2 Mono is a resin printer that’s easy to use and has high printing accuracy. The ELEGOO Mars 2 Mono 3D printer has the following features:\n\n - Long-lasting 2K mono LCD screen\n - Sturdy aluminum body\n - Replaceable resin tank\n## Specifications\n**Technology**: UV Photocuring\n\n**Printing size**: 129x80x150mm\n\n**Maximum printing speed**: 50mm/h\n\n**Layer thickness**: 0.01-0.2mm\n\n**Slicer software**: ChituBox";
export const _ELEGOOMars2MonoTitle = "ELEGOO Mars 2 Mono Resin 3D Printer";
export const _ELEGOOMars3MSLAAltText = "![ELEGOO Mars 3 MSLA resin 3D printer. The printer has a transparent red UV cover, a control panel on the base, and an inverted build platform.](https://cdn.shopify.com/s/files/1/0296/9026/5648/products/pre-orderelegoo-mars-3-ultra-4k-mono-lcd-3d-printer-with-3pcs-fep20-film-3d-printers-elegoo-356741_2048x2048.jpg?v=1637567969)";
export const _ELEGOOMars3MSLADescription = "## Description\nThe ELEGOO Mars 3 MSLA 3D printer is an ideal printer for hobbyists and makers. The Mars 3 MSLA is a resin printer that’s easy to use and has high printing accuracy. The ELEGOO Mars 3 MSLA 3D printer has the following features:\n\n - Long-lasting, high 4K resolution mono LCD screen\n - Large build volume and build plate\n - Quick, highly detailed printing\n## Specifications\n**Technology**: MSLA 3D Stereolithography\n\n**Printing size**: 143.43x89.6x175mm\n\n**Maximum printing speed**: 50mm/h\n\n**Layer thickness**: 0.01-0.2mm\n\n**Slicer software**: ChituBox";
export const _ELEGOOMars3MSLATitle = "ELEGOO Mars 3 MSLA Resin 3D Printer";
export const _ELEGOOSaturnSMonoAltText = "![ELEGOO Saturn S Mono resin 3D printer. The printer has a transparent green UV cover to protect models as they print.](https://cdn.shopify.com/s/files/1/0296/9026/5648/products/elegoo-saturn-s-msla-91-4k-mono-lcd-3d-printer-3d-printers-elegoo-shop-997651_2048x2048.jpg?v=1645180731)";
export const _ELEGOOSaturnSMonoDescription = "## Description\nThe ELEGOO Saturn S Mono 3D printer is an excellent printer for experienced hobbyists and makers. The Saturn S Mono is a resin printer that’s easy to use and has high printing accuracy. The ELEGOO Saturn S Mono 3D printer has the following features:\n\n - Long-lasting, high 4K resolution mono LCD screen\n - Shock absorption unit for stable and accurate printing\n - Replaceable carbon filter to absorb resin fumes\n## Specifications\n**Technology**: LED Display Photocuring\n\n**Printing size**: 196x122x210mm\n\n**Maximum printing speed**: 70mm/h\n\n**Layer thickness**: 0.01-0.15mm\n\n**Slicer software**: ChituBox";
export const _ELEGOOSaturnSMonoTitle = "ELEGOO Saturn S Mono Resin 3D Printer";
export const _WaterWashableResinBeigeAltText = "![ELEGOO Water Washable Photopolymer beige resin in a 1000-gram bottle. A beige model of a building shows the printed colour.](https://m.media-amazon.com/images/I/611t0GKktXL._SL1500_.jpg)";
export const _WaterWashableResinBlackAltText = "![ELEGOO Water Washable Photopolymer black resin in a 1000-gram bottle. A black figurine shows the printed colour.](https://m.media-amazon.com/images/I/61V4yOrh4QL._SL1500_.jpg)";
export const _WaterWashableResinCeramicGreyAltText = "![ELEGOO Water Washable Photopolymer ceramic grey resin in a 1000-gram bottle. A ceramic grey figurine shows the printed colour.](https://m.media-amazon.com/images/I/71NyPwj2QoL._SL1500_.jpg)";
export const _WaterWashableResinClearGreenAltText = "![ELEGOO Water Washable Photopolymer clear green resin in a 1000-gram bottle. A clear green geometric model shows the printed colour.](https://m.media-amazon.com/images/I/71-DqDPUpSL._SL1500_.jpg)";
export const _WaterWashableResinClearRedAltText = "![ELEGOO Water Washable Photopolymer clear red resin in a 1000-gram bottle. A clear red geometric model shows the printed colour.](https://m.media-amazon.com/images/I/7159QwR9-PL._SL1500_.jpg)";
export const _WaterWashableResinDescription = "## Description\nELEGOO Water Washable Resin is ideal for LCD 3D printers. This is a high-precision resin with fast curing times and low shrinkage. It is available in a wide range of vibrant colours.\n\n**Difficulty Level**: Beginner-Intermediate\n\n**Strength**: High\n\n**Flexibility**: High\n\n**Durability**: High\n\n**Shrinkage/Warping**: Low\n\n**Soluble**: Uncured resin is soluble in water\n\n**Food Safe**: No\n\n**Perfect for**: Miniature objects with extra detail, like boardgame pieces; watertight applications; dental applications, like clear aligners and surgical guides\n## Printing Details\n**Technology**: Ideal for LCD, suitable for DLP\n\n**Recommended Setting**:\nBottom exposure: 60s\nNormal exposure: 8s\n## More Details\n**Pros**\n\n - Produces very detailed objects\n - Washable in water—no expensive or harmful cleaners required\n - Fast curing time\n\n**Cons**\n\n - More expensive than filament\n - Requires post-processing";
export const _WaterWashableResinMintGreenAltText = "![ELEGOO Water Washable Photopolymer mint green resin in a 1000-gram bottle. A mint green figurine of a pirate shows the printed colour.](https://m.media-amazon.com/images/I/71GRA6FqG8L._SL1500_.jpg)";
export const _WaterWashableResinSmokyBlackAltText = "![ELEGOO Water Washable Photopolymer smoky black resin in a 1000-gram bottle. A smoky black figurine shows the printed colour.](https://m.media-amazon.com/images/I/61R7Dx3-M0L._SL1500_.jpg)";
export const _WaterWashableResinTitle = "ELEGOO Water Washable Standard Photopolymer Resin (1000g)";
export const _WaterWashableResinWaterBlueAltText = "![ELEGOO Water Washable Photopolymer water blue resin in a 1000-gram bottle. A water blue model of a castle shows the printed colour.](https://m.media-amazon.com/images/I/712TXcIcUKL._SL1500_.jpg)";
export const _WaterWashableResinWhiteAltText = "![ELEGOO Water Washable Photopolymer white resin in a 1000-gram bottle. A white figurine shows the printed colour.](https://m.media-amazon.com/images/I/61EvRs-yXDL._SL1500_.jpg)";
export const _WaterWashableResinYellowAltText = "![ELEGOO Water Washable Photopolymer yellow resin in a 1000-gram bottle. A yellow geometric model shows the printed colour.](https://m.media-amazon.com/images/I/71d0nQeaXcL._SL1500_.jpg)";

export default {
  _ABSFilamentDescription, 
  _ABSFilamentTitle, 
  _NylonFilamentDescription, 
  _NylonFilamentTitle, 
  _PCFilamentDescription, 
  _PCFilamentTitle, 
  _PETGFilamentDescription, 
  _PETGFilamentTitle, 
  _PLAFilamentDescription, 
  _PLAFilamentGlowDescription, 
  _PLAFilamentGlowTitle, 
  _PLAFilamentTitle, 
  _TPEFilamentDescription, 
  _TPEFilamentTitle, 
  _3DPenDescription, 
  _3DPenTitle, 
  _CrealityEnder3AltText, 
  _CrealityEnder3Description, 
  _CrealityEnder3Title, 
  _CrealityEnder3ProAltText, 
  _CrealityEnder3ProDescription, 
  _CrealityEnder3ProTitle, 
  _CrealityEnder3S1AltText, 
  _CrealityEnder3S1Description, 
  _CrealityEnder3S1Title, 
  _CrealityEnder3V2AltText, 
  _CrealityEnder3V2Description, 
  _CrealityEnder3V2Title, 
  _ELEGOOMars2MonoAltText, 
  _ELEGOOMars2MonoDescription, 
  _ELEGOOMars2MonoTitle, 
  _ELEGOOMars3MSLAAltText, 
  _ELEGOOMars3MSLADescription, 
  _ELEGOOMars3MSLATitle, 
  _ELEGOOSaturnSMonoAltText, 
  _ELEGOOSaturnSMonoDescription, 
  _ELEGOOSaturnSMonoTitle, 
  _WaterWashableResinBeigeAltText, 
  _WaterWashableResinBlackAltText, 
  _WaterWashableResinCeramicGreyAltText, 
  _WaterWashableResinClearGreenAltText, 
  _WaterWashableResinClearRedAltText, 
  _WaterWashableResinDescription, 
  _WaterWashableResinMintGreenAltText, 
  _WaterWashableResinSmokyBlackAltText, 
  _WaterWashableResinTitle, 
  _WaterWashableResinWaterBlueAltText, 
  _WaterWashableResinWhiteAltText, 
  _WaterWashableResinYellowAltText
};