export enum ROUTES {
  HOME = '/',
  FAQ = '/faq',
  ABOUT = '/about',
  CHECKOUT = '/cart',
  COMPANY = '/company',
  CONTACT = '/contact',
  LANDING_PAGE = '/welcome',
  CATEGORIES = '/category/:name',
  RETURN_POLICY = '/return-policy',
  PRIVACY_POLICY = '/privacy-policy',
  SUSTAINABILITY = '/sustainability',
  DELIVERY_POLICY = '/delivery-policy',
  TERMS_AND_CONDITIONS = '/terms-and-conditions',
  WARRANTY_REPAIR_POLICY = '/warranty-repair-policy',
  PRODUCT = '/category/:category/product/:id/:articleId/:name',
}
